/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PassengersRouteImport } from './routes/passengers'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as SeatsRouteImport } from './routes/seats'
import { Route as TrainsRouteImport } from './routes/trains'
import { Route as InfoTopicRouteImport } from './routes/info.$topic'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PassengersRoute = PassengersRouteImport.update({
  id: '/passengers',
  path: '/passengers',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const SeatsRoute = SeatsRouteImport.update({
  id: '/seats',
  path: '/seats',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainsRoute = TrainsRouteImport.update({
  id: '/trains',
  path: '/trains',
  getParentRoute: () => rootRouteImport,
} as any)
const InfoTopicRoute = InfoTopicRouteImport.update({
  id: '/info/$topic',
  path: '/info/$topic',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/passengers': typeof PassengersRoute
  '/payment': typeof PaymentRoute
  '/seats': typeof SeatsRoute
  '/trains': typeof TrainsRoute
  '/info/$topic': typeof InfoTopicRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/passengers': typeof PassengersRoute
  '/payment': typeof PaymentRoute
  '/seats': typeof SeatsRoute
  '/trains': typeof TrainsRoute
  '/info/$topic': typeof InfoTopicRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/passengers': typeof PassengersRoute
  '/payment': typeof PaymentRoute
  '/seats': typeof SeatsRoute
  '/trains': typeof TrainsRoute
  '/info/$topic': typeof InfoTopicRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/passengers' | '/payment' | '/seats' | '/trains' | '/info/$topic'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/passengers' | '/payment' | '/seats' | '/trains' | '/info/$topic'
  id:
    | '__root__'
    | '/'
    | '/passengers'
    | '/payment'
    | '/seats'
    | '/trains'
    | '/info/$topic'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PassengersRoute: typeof PassengersRoute
  PaymentRoute: typeof PaymentRoute
  SeatsRoute: typeof SeatsRoute
  TrainsRoute: typeof TrainsRoute
  InfoTopicRoute: typeof InfoTopicRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passengers': {
      id: '/passengers'
      path: '/passengers'
      fullPath: '/passengers'
      preLoaderRoute: typeof PassengersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seats': {
      id: '/seats'
      path: '/seats'
      fullPath: '/seats'
      preLoaderRoute: typeof SeatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trains': {
      id: '/trains'
      path: '/trains'
      fullPath: '/trains'
      preLoaderRoute: typeof TrainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info/$topic': {
      id: '/info/$topic'
      path: '/info/$topic'
      fullPath: '/info/$topic'
      preLoaderRoute: typeof InfoTopicRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PassengersRoute: PassengersRoute,
  PaymentRoute: PaymentRoute,
  SeatsRoute: SeatsRoute,
  TrainsRoute: TrainsRoute,
  InfoTopicRoute: InfoTopicRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
